version: '3.3'
services:
    todo-list:
        ports:
            - 5000:5000
        container_name: todo-list
        volumes:
            - sqlite:/todo-list/instance
        image: jiaju051631/todo-list:0.2
volumes:
    sqlite:
        driver: local